import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#717a83] shadow-2xl">
        <ul className="flex  w-100 justify-around my-6 ">
          <Link
            className="bg-black hover:bg-purple-400 shadow-lg rounded-3xl py-3 px-10 text-white"
            href="/Home"
          >
            Home
          </Link>

          <Link
            className="bg-black hover:bg-purple-400 shadow-lg rounded-3xl py-3 px-10 text-white"
            href="/About"
          >
            About
          </Link>

          <Link
            className="bg-black hover:bg-purple-400  hover:shadow-2xl rounded-3xl py-3 px-10 text-white"
            href="/Contact"
          >
            Contact
          </Link>

          <Link
            className="bg-black hover:bg-purple-400 shadow-lg rounded-3xl py-3 px-10 text-white"
            href="/Services"
          >
            Services
          </Link>
        </ul>
        <div className="h-[89.9vh]">{children}</div>
      </body>
    </html>
  );
}
